name: test-action
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: python install
        uses: actions/setup-python@v4
        with:  
          python-version: '3.10'
      - name: run
        run: pip install pytest
            pytest
